/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { AreaFront } from './models/area-front';
export { AreaRequest } from './models/area-request';
export { Artista } from './models/artista';
export { ArtistaFront } from './models/artista-front';
export { ArtistaFrontImg } from './models/artista-front-img';
export { ArtistaRequest } from './models/artista-request';
export { AuthenticationRequest } from './models/authentication-request';
export { AuthenticationResponse } from './models/authentication-response';
export { ListArtist } from './models/list-artist';
export { Opera } from './models/opera';
export { OperaFront } from './models/opera-front';
export { OperaRequest } from './models/opera-request';
export { RegistrationRequest } from './models/registration-request';
export { UserFront } from './models/user-front';
export { UserResponse } from './models/user-response';
