/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArtistaRequest {
  cognome: string;
  dataDiMorte?: string;
  dataDiNascita: string;
  luogoDiNascita: string;
  name: string;
}
