/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArtistaFrontImg {
  cognome?: string;
  id?: number;
  img?: string;
  nome?: string;
}
