/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ArtistaFront } from '../models/artista-front';
export interface ListArtist {
  lista?: Array<ArtistaFront>;
}
