/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Artista } from '../models/artista';
export interface Opera {
  anno?: number;
  artista?: Artista;
  id?: number;
  immagine?: string;
  posizione?: number;
  tecnica?: string;
  title?: string;
}
