/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RegistrationRequest {
  codiceFiscale: string;
  cognome: string;
  dataNascita: string;
  email: string;
  luogoDiNascita: string;
  nome: string;
  password: string;
}
