/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  cognome?: string;
  email?: string;
  nome?: string;
  url_pic?: string;
}
