/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperaFront } from '../../models/opera-front';

export interface GetOpera$Params {
  idOpera: number;
}

export function getOpera(http: HttpClient, rootUrl: string, params: GetOpera$Params, context?: HttpContext): Observable<StrictHttpResponse<OperaFront>> {
  const rb = new RequestBuilder(rootUrl, getOpera.PATH, 'get');
  if (params) {
    rb.query('idOpera', params.idOpera, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperaFront>;
    })
  );
}

getOpera.PATH = '/frontEnd/getOpera';
