/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArtistaCut } from '../../models/artista-cut';

export interface GetArtista$Params {
  idArt: number;
}

export function getArtista(http: HttpClient, rootUrl: string, params: GetArtista$Params, context?: HttpContext): Observable<StrictHttpResponse<ArtistaCut>> {
  const rb = new RequestBuilder(rootUrl, getArtista.PATH, 'get');
  if (params) {
    rb.query('idArt', params.idArt, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArtistaCut>;
    })
  );
}

getArtista.PATH = '/frontEnd/getArtista';
