/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { addOperaAdarea } from '../fn/admin-controller/add-opera-adarea';
import { AddOperaAdarea$Params } from '../fn/admin-controller/add-opera-adarea';
import { Artista } from '../models/artista';
import { ArtistaFrontImg } from '../models/artista-front-img';
import { assegnaAreaACuratore } from '../fn/admin-controller/assegna-area-a-curatore';
import { AssegnaAreaACuratore$Params } from '../fn/admin-controller/assegna-area-a-curatore';
import { changeCurtorToArea } from '../fn/admin-controller/change-curtor-to-area';
import { ChangeCurtorToArea$Params } from '../fn/admin-controller/change-curtor-to-area';
import { changeOwnerToOpera } from '../fn/admin-controller/change-owner-to-opera';
import { ChangeOwnerToOpera$Params } from '../fn/admin-controller/change-owner-to-opera';
import { creaArea } from '../fn/admin-controller/crea-area';
import { CreaArea$Params } from '../fn/admin-controller/crea-area';
import { creaArtista } from '../fn/admin-controller/crea-artista';
import { CreaArtista$Params } from '../fn/admin-controller/crea-artista';
import { creaOpera } from '../fn/admin-controller/crea-opera';
import { CreaOpera$Params } from '../fn/admin-controller/crea-opera';
import { delArea } from '../fn/admin-controller/del-area';
import { DelArea$Params } from '../fn/admin-controller/del-area';
import { deleteArtista } from '../fn/admin-controller/delete-artista';
import { DeleteArtista$Params } from '../fn/admin-controller/delete-artista';
import { deleteOpera } from '../fn/admin-controller/delete-opera';
import { DeleteOpera$Params } from '../fn/admin-controller/delete-opera';
import { getAllArtistForDisplay } from '../fn/admin-controller/get-all-artist-for-display';
import { GetAllArtistForDisplay$Params } from '../fn/admin-controller/get-all-artist-for-display';
import { getAllArtistForMenu } from '../fn/admin-controller/get-all-artist-for-menu';
import { GetAllArtistForMenu$Params } from '../fn/admin-controller/get-all-artist-for-menu';
import { getAllCuraFree } from '../fn/admin-controller/get-all-cura-free';
import { GetAllCuraFree$Params } from '../fn/admin-controller/get-all-cura-free';
import { getAllFree } from '../fn/admin-controller/get-all-free';
import { GetAllFree$Params } from '../fn/admin-controller/get-all-free';
import { getAllOpereForDisplay } from '../fn/admin-controller/get-all-opere-for-display';
import { GetAllOpereForDisplay$Params } from '../fn/admin-controller/get-all-opere-for-display';
import { getArtistaDaMod } from '../fn/admin-controller/get-artista-da-mod';
import { GetArtistaDaMod$Params } from '../fn/admin-controller/get-artista-da-mod';
import { getOperaDaMod } from '../fn/admin-controller/get-opera-da-mod';
import { GetOperaDaMod$Params } from '../fn/admin-controller/get-opera-da-mod';
import { ListArtist } from '../models/list-artist';
import { modArtista } from '../fn/admin-controller/mod-artista';
import { ModArtista$Params } from '../fn/admin-controller/mod-artista';
import { modOpera } from '../fn/admin-controller/mod-opera';
import { ModOpera$Params } from '../fn/admin-controller/mod-opera';
import { OperaFront } from '../models/opera-front';
import { removeAreaToCurator } from '../fn/admin-controller/remove-area-to-curator';
import { RemoveAreaToCurator$Params } from '../fn/admin-controller/remove-area-to-curator';
import { testController } from '../fn/admin-controller/test-controller';
import { TestController$Params } from '../fn/admin-controller/test-controller';
import { UserFront } from '../models/user-front';

@Injectable({ providedIn: 'root' })
export class AdminControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `creaOpera()` */
  static readonly CreaOperaPath = '/admin/creaOpera';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `creaOpera()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  creaOpera$Response(params: CreaOpera$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return creaOpera(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `creaOpera$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  creaOpera(params: CreaOpera$Params, context?: HttpContext): Observable<{
}> {
    return this.creaOpera$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `creaArtista()` */
  static readonly CreaArtistaPath = '/admin/creaArtista';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `creaArtista()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  creaArtista$Response(params?: CreaArtista$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return creaArtista(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `creaArtista$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  creaArtista(params?: CreaArtista$Params, context?: HttpContext): Observable<{
}> {
    return this.creaArtista$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `creaArea()` */
  static readonly CreaAreaPath = '/admin/creaArea';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `creaArea()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  creaArea$Response(params: CreaArea$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return creaArea(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `creaArea$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  creaArea(params: CreaArea$Params, context?: HttpContext): Observable<{
}> {
    return this.creaArea$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `assegnaAreaACuratore()` */
  static readonly AssegnaAreaACuratorePath = '/admin/assegnaAreaACuratore';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `assegnaAreaACuratore()` instead.
   *
   * This method doesn't expect any request body.
   */
  assegnaAreaACuratore$Response(params: AssegnaAreaACuratore$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return assegnaAreaACuratore(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `assegnaAreaACuratore$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  assegnaAreaACuratore(params: AssegnaAreaACuratore$Params, context?: HttpContext): Observable<{
}> {
    return this.assegnaAreaACuratore$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `addOperaAdarea()` */
  static readonly AddOperaAdareaPath = '/admin/addOperaAdArea';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `addOperaAdarea()` instead.
   *
   * This method doesn't expect any request body.
   */
  addOperaAdarea$Response(params: AddOperaAdarea$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return addOperaAdarea(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `addOperaAdarea$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  addOperaAdarea(params: AddOperaAdarea$Params, context?: HttpContext): Observable<{
}> {
    return this.addOperaAdarea$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `modOpera()` */
  static readonly ModOperaPath = '/admin/modOpera';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `modOpera()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modOpera$Response(params: ModOpera$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return modOpera(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `modOpera$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modOpera(params: ModOpera$Params, context?: HttpContext): Observable<{
}> {
    return this.modOpera$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `modArtista()` */
  static readonly ModArtistaPath = '/admin/modArtista';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `modArtista()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modArtista$Response(params: ModArtista$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return modArtista(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `modArtista$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  modArtista(params: ModArtista$Params, context?: HttpContext): Observable<{
}> {
    return this.modArtista$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `changeOwnerToOpera()` */
  static readonly ChangeOwnerToOperaPath = '/admin/changeOwnerToOpera';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeOwnerToOpera()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeOwnerToOpera$Response(params: ChangeOwnerToOpera$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return changeOwnerToOpera(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeOwnerToOpera$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeOwnerToOpera(params: ChangeOwnerToOpera$Params, context?: HttpContext): Observable<{
}> {
    return this.changeOwnerToOpera$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `changeCurtorToArea()` */
  static readonly ChangeCurtorToAreaPath = '/admin/changeCurtorTOArea';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `changeCurtorToArea()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeCurtorToArea$Response(params: ChangeCurtorToArea$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return changeCurtorToArea(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `changeCurtorToArea$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  changeCurtorToArea(params: ChangeCurtorToArea$Params, context?: HttpContext): Observable<{
}> {
    return this.changeCurtorToArea$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `testController()` */
  static readonly TestControllerPath = '/admin/testController';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testController()` instead.
   *
   * This method doesn't expect any request body.
   */
  testController$Response(params?: TestController$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return testController(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testController$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testController(params?: TestController$Params, context?: HttpContext): Observable<{
}> {
    return this.testController$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getOperaDaMod()` */
  static readonly GetOperaDaModPath = '/admin/getOperaDaMod';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getOperaDaMod()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperaDaMod$Response(params: GetOperaDaMod$Params, context?: HttpContext): Observable<StrictHttpResponse<OperaFront>> {
    return getOperaDaMod(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getOperaDaMod$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getOperaDaMod(params: GetOperaDaMod$Params, context?: HttpContext): Observable<OperaFront> {
    return this.getOperaDaMod$Response(params, context).pipe(
      map((r: StrictHttpResponse<OperaFront>): OperaFront => r.body)
    );
  }

  /** Path part for operation `getAllCuraFree()` */
  static readonly GetAllCuraFreePath = '/admin/getCuraDisponibili';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllCuraFree()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCuraFree$Response(params?: GetAllCuraFree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserFront>>> {
    return getAllCuraFree(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllCuraFree$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllCuraFree(params?: GetAllCuraFree$Params, context?: HttpContext): Observable<Array<UserFront>> {
    return this.getAllCuraFree$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<UserFront>>): Array<UserFront> => r.body)
    );
  }

  /** Path part for operation `getArtistaDaMod()` */
  static readonly GetArtistaDaModPath = '/admin/getArtistaForMod';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getArtistaDaMod()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArtistaDaMod$Response(params: GetArtistaDaMod$Params, context?: HttpContext): Observable<StrictHttpResponse<Artista>> {
    return getArtistaDaMod(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getArtistaDaMod$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getArtistaDaMod(params: GetArtistaDaMod$Params, context?: HttpContext): Observable<Artista> {
    return this.getArtistaDaMod$Response(params, context).pipe(
      map((r: StrictHttpResponse<Artista>): Artista => r.body)
    );
  }

  /** Path part for operation `getAllFree()` */
  static readonly GetAllFreePath = '/admin/getAllOpereLibere';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllFree()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFree$Response(params?: GetAllFree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperaFront>>> {
    return getAllFree(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllFree$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllFree(params?: GetAllFree$Params, context?: HttpContext): Observable<Array<OperaFront>> {
    return this.getAllFree$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OperaFront>>): Array<OperaFront> => r.body)
    );
  }

  /** Path part for operation `getAllOpereForDisplay()` */
  static readonly GetAllOpereForDisplayPath = '/admin/getAllOpereForDisplay';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllOpereForDisplay()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOpereForDisplay$Response(params?: GetAllOpereForDisplay$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OperaFront>>> {
    return getAllOpereForDisplay(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllOpereForDisplay$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllOpereForDisplay(params?: GetAllOpereForDisplay$Params, context?: HttpContext): Observable<Array<OperaFront>> {
    return this.getAllOpereForDisplay$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OperaFront>>): Array<OperaFront> => r.body)
    );
  }

  /** Path part for operation `getAllArtistForMenu()` */
  static readonly GetAllArtistForMenuPath = '/admin/getAllArtistForMenu';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllArtistForMenu()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArtistForMenu$Response(params?: GetAllArtistForMenu$Params, context?: HttpContext): Observable<StrictHttpResponse<ListArtist>> {
    return getAllArtistForMenu(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllArtistForMenu$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArtistForMenu(params?: GetAllArtistForMenu$Params, context?: HttpContext): Observable<ListArtist> {
    return this.getAllArtistForMenu$Response(params, context).pipe(
      map((r: StrictHttpResponse<ListArtist>): ListArtist => r.body)
    );
  }

  /** Path part for operation `getAllArtistForDisplay()` */
  static readonly GetAllArtistForDisplayPath = '/admin/getAllArtistForDisplay';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAllArtistForDisplay()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArtistForDisplay$Response(params?: GetAllArtistForDisplay$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ArtistaFrontImg>>> {
    return getAllArtistForDisplay(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAllArtistForDisplay$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAllArtistForDisplay(params?: GetAllArtistForDisplay$Params, context?: HttpContext): Observable<Array<ArtistaFrontImg>> {
    return this.getAllArtistForDisplay$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ArtistaFrontImg>>): Array<ArtistaFrontImg> => r.body)
    );
  }

  /** Path part for operation `removeAreaToCurator()` */
  static readonly RemoveAreaToCuratorPath = '/admin/removeAreaFromCurator';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removeAreaToCurator()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeAreaToCurator$Response(params: RemoveAreaToCurator$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return removeAreaToCurator(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removeAreaToCurator$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  removeAreaToCurator(params: RemoveAreaToCurator$Params, context?: HttpContext): Observable<{
}> {
    return this.removeAreaToCurator$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `deleteOpera()` */
  static readonly DeleteOperaPath = '/admin/deleteOpera';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteOpera()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOpera$Response(params: DeleteOpera$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteOpera(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteOpera$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteOpera(params: DeleteOpera$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteOpera$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `deleteArtista()` */
  static readonly DeleteArtistaPath = '/admin/deleteArtista';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `deleteArtista()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArtista$Response(params: DeleteArtista$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return deleteArtista(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `deleteArtista$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  deleteArtista(params: DeleteArtista$Params, context?: HttpContext): Observable<{
}> {
    return this.deleteArtista$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `delArea()` */
  static readonly DelAreaPath = '/admin/delArea';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `delArea()` instead.
   *
   * This method doesn't expect any request body.
   */
  delArea$Response(params: DelArea$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return delArea(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `delArea$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  delArea(params: DelArea$Params, context?: HttpContext): Observable<{
}> {
    return this.delArea$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

}
