/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getCuratorData } from '../fn/curator-controller/get-curator-data';
import { GetCuratorData$Params } from '../fn/curator-controller/get-curator-data';
import { testSicurezza } from '../fn/curator-controller/test-sicurezza';
import { TestSicurezza$Params } from '../fn/curator-controller/test-sicurezza';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class CuratorControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `testSicurezza()` */
  static readonly TestSicurezzaPath = '/curator/test';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `testSicurezza()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza$Response(params?: TestSicurezza$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
    return testSicurezza(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `testSicurezza$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  testSicurezza(params?: TestSicurezza$Params, context?: HttpContext): Observable<{
}> {
    return this.testSicurezza$Response(params, context).pipe(
      map((r: StrictHttpResponse<{
}>): {
} => r.body)
    );
  }

  /** Path part for operation `getCuratorData()` */
  static readonly GetCuratorDataPath = '/curator/getCuratorData';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCuratorData()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCuratorData$Response(params?: GetCuratorData$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    return getCuratorData(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCuratorData$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCuratorData(params?: GetCuratorData$Params, context?: HttpContext): Observable<UserResponse> {
    return this.getCuratorData$Response(params, context).pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

}
