/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AreaFront } from '../models/area-front';
import { checkIfOwner } from '../fn/front-end-controller/check-if-owner';
import { CheckIfOwner$Params } from '../fn/front-end-controller/check-if-owner';
import { getAree } from '../fn/front-end-controller/get-aree';
import { GetAree$Params } from '../fn/front-end-controller/get-aree';
import { isAdmin } from '../fn/front-end-controller/is-admin';
import { IsAdmin$Params } from '../fn/front-end-controller/is-admin';

@Injectable({ providedIn: 'root' })
export class FrontEndControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `isAdmin()` */
  static readonly IsAdminPath = '/frontEnd/isAdmin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `isAdmin()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdmin$Response(params?: IsAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return isAdmin(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `isAdmin$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  isAdmin(params?: IsAdmin$Params, context?: HttpContext): Observable<boolean> {
    return this.isAdmin$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `getAree()` */
  static readonly GetAreePath = '/frontEnd/getAree';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAree()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAree$Response(params?: GetAree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AreaFront>>> {
    return getAree(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAree$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAree(params?: GetAree$Params, context?: HttpContext): Observable<Array<AreaFront>> {
    return this.getAree$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AreaFront>>): Array<AreaFront> => r.body)
    );
  }

  /** Path part for operation `checkIfOwner()` */
  static readonly CheckIfOwnerPath = '/frontEnd/checkIfCurator';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `checkIfOwner()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkIfOwner$Response(params?: CheckIfOwner$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return checkIfOwner(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `checkIfOwner$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  checkIfOwner(params?: CheckIfOwner$Params, context?: HttpContext): Observable<boolean> {
    return this.checkIfOwner$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
