/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Artista } from '../../models/artista';

export interface GetArtistaDaMod$Params {
  idArt: number;
}

export function getArtistaDaMod(http: HttpClient, rootUrl: string, params: GetArtistaDaMod$Params, context?: HttpContext): Observable<StrictHttpResponse<Artista>> {
  const rb = new RequestBuilder(rootUrl, getArtistaDaMod.PATH, 'get');
  if (params) {
    rb.query('idArt', params.idArt, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Artista>;
    })
  );
}

getArtistaDaMod.PATH = '/admin/getArtistaForMod';
