/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArtistaFrontImg } from '../../models/artista-front-img';

export interface GetAllArtistForDisplay$Params {
}

export function getAllArtistForDisplay(http: HttpClient, rootUrl: string, params?: GetAllArtistForDisplay$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ArtistaFrontImg>>> {
  const rb = new RequestBuilder(rootUrl, getAllArtistForDisplay.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ArtistaFrontImg>>;
    })
  );
}

getAllArtistForDisplay.PATH = '/admin/getAllArtistForDisplay';
