/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserFront } from '../../models/user-front';

export interface GetAllCuraFree$Params {
}

export function getAllCuraFree(http: HttpClient, rootUrl: string, params?: GetAllCuraFree$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserFront>>> {
  const rb = new RequestBuilder(rootUrl, getAllCuraFree.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserFront>>;
    })
  );
}

getAllCuraFree.PATH = '/admin/getCuraDisponibili';
